#!/bin/bash

./xmlrpc-client.pl -w 1 -c 3 -h localhost -p 8080 -s siebfoobar -a SRProc
./xmlrpc-client.pl -w 1 -c 3 -h localhost -p 8080 -s siebfoobar -a CommSessionMgr
./xmlrpc-client.pl -w 1 -c 3 -h localhost -p 8080 -s siebfoobar -a WorkActn
./xmlrpc-client.pl -w 1 -c 3 -h localhost -p 8080 -s siebfoobar -a htimprmObjMgr_ptb
./xmlrpc-client.pl -w 1 -c 3 -h localhost -p 8080 -s siebfoobar -a CommInboundRcvr
./xmlrpc-client.pl -w 1 -c 3 -h localhost -p 8080 -s siebfoobar -a WfRecvMgr
./xmlrpc-client.pl -w 1 -c 3 -h localhost -p 8080 -s siebfoobar -a WfProcBatchMgr
./xmlrpc-client.pl -w 1 -c 3 -h localhost -p 8080 -s siebfoobar -a GenTrig
./xmlrpc-client.pl -w 1 -c 3 -h localhost -p 8080 -s siebfoobar -a CustomAppObjMgr_ptb
./xmlrpc-client.pl -w 1 -c 3 -h localhost -p 8080 -s siebfoobar -a ADMObjMgr_enu
./xmlrpc-client.pl -w 1 -c 3 -h localhost -p 8080 -s siebfoobar -a WorkMonSWI
./xmlrpc-client.pl -w 1 -c 3 -h localhost -p 8080 -s siebfoobar -a htimObjMgr_enu
./xmlrpc-client.pl -w 1 -c 3 -h localhost -p 8080 -s siebfoobar -a ServerMgr
./xmlrpc-client.pl -w 1 -c 3 -h localhost -p 8080 -s siebfoobar -a EIM
./xmlrpc-client.pl -w 1 -c 3 -h localhost -p 8080 -s siebfoobar -a htimprmObjMgr_enu
./xmlrpc-client.pl -w 1 -c 3 -h localhost -p 8080 -s siebfoobar -a BusIntMgr
./xmlrpc-client.pl -w 1 -c 3 -h localhost -p 8080 -s siebfoobar -a ListImportSvcMgr
./xmlrpc-client.pl -w 1 -c 3 -h localhost -p 8080 -s siebfoobar -a WfProcMgr
./xmlrpc-client.pl -w 1 -c 3 -h localhost -p 8080 -s siebfoobar -a BusIntBatchMgr
./xmlrpc-client.pl -w 1 -c 3 -h localhost -p 8080 -s siebfoobar -a CommOutboundMgr
./xmlrpc-client.pl -w 1 -c 3 -h localhost -p 8080 -s siebfoobar -a CommInboundProcessor
./xmlrpc-client.pl -w 1 -c 3 -h localhost -p 8080 -s siebfoobar -a SRBroker
./xmlrpc-client.pl -w 1 -c 3 -h localhost -p 8080 -s siebfoobar -a JMSReceiver
./xmlrpc-client.pl -w 1 -c 3 -h localhost -p 8080 -s siebfoobar -a ADMProc
./xmlrpc-client.pl -w 1 -c 3 -h localhost -p 8080 -s siebfoobar -a FSMSrvr
./xmlrpc-client.pl -w 1 -c 3 -h localhost -p 8080 -s siebfoobar -a ADMObjMgr_ptb
./xmlrpc-client.pl -w 1 -c 3 -h localhost -p 8080 -s siebfoobar -a SCBroker
./xmlrpc-client.pl -w 1 -c 3 -h localhost -p 8080 -s siebfoobar -a PDbXtract
./xmlrpc-client.pl -w 1 -c 3 -h localhost -p 8080 -s siebfoobar -a CommConfigMgr
./xmlrpc-client.pl -w 1 -c 3 -h localhost -p 8080 -s siebfoobar -a RepAgent
./xmlrpc-client.pl -w 1 -c 3 -h localhost -p 8080 -s siebfoobar -a EAIObjMgr_enu
./xmlrpc-client.pl -w 1 -c 3 -h localhost -p 8080 -s siebfoobar -a GenNewDb
./xmlrpc-client.pl -w 1 -c 3 -h localhost -p 8080 -s siebfoobar -a AdminNotify
./xmlrpc-client.pl -w 1 -c 3 -h localhost -p 8080 -s siebfoobar -a SvrTblCleanup
./xmlrpc-client.pl -w 1 -c 3 -h localhost -p 8080 -s siebfoobar -a EAIObjMgr_ptb
./xmlrpc-client.pl -w 1 -c 3 -h localhost -p 8080 -s siebfoobar -a SvrTaskPersist
./xmlrpc-client.pl -w 1 -c 3 -h localhost -p 8080 -s siebfoobar -a MailMgr
./xmlrpc-client.pl -w 1 -c 3 -h localhost -p 8080 -s siebfoobar -a ADMBatchProc
./xmlrpc-client.pl -w 1 -c 3 -h localhost -p 8080 -s siebfoobar -a DbXtract
./xmlrpc-client.pl -w 1 -c 3 -h localhost -p 8080 -s siebfoobar -a htimObjMgr_ptb
./xmlrpc-client.pl -w 1 -c 3 -h localhost -p 8080 -s siebfoobar -a WorkMon
./xmlrpc-client.pl -w 1 -c 3 -h localhost -p 8080 -s siebfoobar -a CustomAppObjMgr_enu
./xmlrpc-client.pl -w 1 -c 3 -h localhost -p 8080 -s siebfoobar -a TaskLogCleanup
